# slicing in array

# slicing in 1d array

In [3]:
import  numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[0:3])
print(arr[1:5])

[1 2 3]
[2 3 4 5]


# stepping 

In [5]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])
print(arr[::3])

[1 3 5 7]
[1 4 7]


# slicing in 2d array

In [12]:
arr = np.array([[1,2,3,4,5],[60,70,80,90,100]])
print(arr[1,1:4])

[70 80 90]


# chaking the data type in array 

In [13]:
arr = np.array([1,2,3,4,5,56])
print(arr.dtype)

int32


In [14]:
arr = np.array(["animal","dog","cat","cow"])
print(arr.dtype)

<U6


# creating a array with the defined datata type

In [20]:
import numpy as np

arr = np.array([1,2,3,4], dtype = "S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


create an array with a defined data type 


In [23]:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# numpy array shape

the shape of an array is the no of element in each dimension

# print the shape of 2d array

In [24]:
arr = np.array ([[1,2,3,4,5],[10,20,30,40,50]])
print(arr.shape)

(2, 5)


In [25]:
arr = np.array ([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]]])
print(arr.shape)

(1, 3, 5)


# joining the numpy arrays

# joining for 1d array

In [26]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)


[1 2 3 4 5 6]


# joining for 2d array

for axis 1

In [27]:
arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[10,20,30],[40,50,60]])

arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


forc axis 0

In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[10,20,30],[40,50,60]])

arr = np.concatenate((arr1,arr2),axis = 0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


# spliting Numpy arrays

# spliting the array in  3 parts 

In [29]:
arr = np.array([1,2,3,4,5,6])

newarray = np.array_split(arr,3)
print(newarray)


[array([1, 2]), array([3, 4]), array([5, 6])]


# spliting the array in 4 parts

In [30]:
arr = np.array([1,2,3,4,5,6,7,8])

newarray = np.array_split(arr,4)
print(newarray)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [31]:
arr = np.array([1,2,3,4,5,6])

newarray = np.array_split(arr,4)
print(newarray)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel and flatten

converts the multidimentional array in 1d array

In [33]:
arr = np.array ([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]]])
print(arr)
print("dimension is",arr.ndim)
n = arr.ravel()
print(n)
print("dimension of new array",n.ndim)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]
  [100 200 300 400 500]]]
dimension is 3
[  1   2   3   4   5  10  20  30  40  50 100 200 300 400 500]
dimension of new array 1


In [34]:
arr = np.array ([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]]])
print(arr)
print("dimension is",arr.ndim)
n = arr.flatten()
print(n)
print("dimension of new array",n.ndim)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]
  [100 200 300 400 500]]]
dimension is 3
[  1   2   3   4   5  10  20  30  40  50 100 200 300 400 500]
dimension of new array 1


In [35]:
c = np.array([[[[12,23,33],[55,66,88],[89,90,50],[89,55,66]]]])
print(c)
print("dimension is",c.ndim)
n = c.ravel()
print(n)
print("dimension of new array",n.ndim)



[[[[12 23 33]
   [55 66 88]
   [89 90 50]
   [89 55 66]]]]
dimension is 4
[12 23 33 55 66 88 89 90 50 89 55 66]
dimension of new array 1


In [36]:
c = np.array([[[[12,23,33],[55,66,88],[89,90,50],[89,55,66]]]])
print(c)
print("dimension is",c.ndim)
n = c.flatten()
print(n)
print("dimension of new array",n.ndim)


[[[[12 23 33]
   [55 66 88]
   [89 90 50]
   [89 55 66]]]]
dimension is 4
[12 23 33 55 66 88 89 90 50 89 55 66]
dimension of new array 1


# unique function

In [38]:
k = np.array([1,2,3,4,56,8,9,20,54,52,54,56,4,140,45,104])
print(k)
x = np.unique(k)
print(x)


[  1   2   3   4  56   8   9  20  54  52  54  56   4 140  45 104]
[  1   2   3   4   8   9  20  45  52  54  56 104 140]


# for indexing position ( if we want to print index position )

In [39]:
k = np.array([1,2,3,4,56,8,9,20,54,52,54,56,4,140,45,104])
print(k)
x = np.unique(k,return_index=True)
print(x)


[  1   2   3   4  56   8   9  20  54  52  54  56   4 140  45 104]
(array([  1,   2,   3,   4,   8,   9,  20,  45,  52,  54,  56, 104, 140]), array([ 0,  1,  2,  3,  5,  6,  7, 14,  9,  8,  4, 15, 13], dtype=int64))


# for repetation  count

In [40]:
k = np.array([1,2,3,4,56,8,9,20,54,52,54,56,4,140,45,104])
print(k)
x = np.unique(k,return_index=True, return_counts=True)
print(x)


[  1   2   3   4  56   8   9  20  54  52  54  56   4 140  45 104]
(array([  1,   2,   3,   4,   8,   9,  20,  45,  52,  54,  56, 104, 140]), array([ 0,  1,  2,  3,  5,  6,  7, 14,  9,  8,  4, 15, 13], dtype=int64), array([1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1], dtype=int64))


# delete

for 1d array

In [42]:
a = np.array([12,13,14,15])
b = np.delete(a,[1])
print(b)

[12 14 15]


for 2d array

In [46]:
a = np.array([[12,13,14,15],[11,16,17,18],[33,55,66,77]])
print(a)
b = np.delete(a,2, axis=0)
print()
print(b)

[[12 13 14 15]
 [11 16 17 18]
 [33 55 66 77]]

[[12 13 14 15]
 [11 16 17 18]]


In [47]:
a = np.array([[12,13,14,15],[11,16,17,18],[33,55,66,77]])
print(a)
b = np.delete(a,2, axis=1)
print()
print(b)

[[12 13 14 15]
 [11 16 17 18]
 [33 55 66 77]]

[[12 13 15]
 [11 16 18]
 [33 55 77]]
