In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# tuple passing in the array

In [3]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# dimension in array

In [4]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1 d array

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


# 2d array

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [11]:
arr = np.array([[1,2],[4,5]])
print(arr)
print(type(arr))
print(arr.ndmin)

[[1 2]
 [4 5]]
<class 'numpy.ndarray'>
2


# 3d array

In [12]:
arr = np.array([[[1,2],[4,5],[5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2]
  [4 5]
  [5 6]]]
<class 'numpy.ndarray'>
3


# create higher dimension array 

create a 5 dimension array and verify that it is 5 dimension 

In [20]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)

print(arr)

print("dimension of the array:", arr.ndim)

[[[[[1 2 3 4]]]]]
dimension of the array: 5


In [21]:
arr = np.array([[[[1,2,3,4]]]])

print(arr)

print("dimension of the array:", arr.ndim)

[[[[1 2 3 4]]]]
dimension of the array: 4


# indexing in the array 

In [22]:
arr =  np.array([1,2,3,4,5])
print (arr[0])

1


In [23]:
arr =  np.array([1,2,3,4,5])
print (arr[1])

2


In [25]:
arr =  np.array([1,2,3,4,5])
print (arr[2])

3


In [26]:
arr =  np.array([1,2,3,4,5])
print (arr[-1])

5


# get the 3rd 6 th and 8th element from the array and add them 

In [27]:
arr =  np.array([1,2,3,4,5,86,65,6,9,6])
print (arr[2])
print (arr[5])
print (arr[7])
print (arr[2]+arr[5]+arr[7])

3
86
6
95


# indexing in 2d array 

In [29]:
arr = np.array([[1,2,3],[4,5,6]])
print ("2nd element of the 1st row:",arr[0,1])
print ("1st element of the 2nd row:",arr[1,0])

2nd element of the 1st row: 2
1st element of the 2nd row: 4


# add the 1st element of row 1 and last element of the 2nd row

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
print ("2nd element of the 1st row:",arr[0,0])
print ("1st element of the 2nd row:",arr[1,-1])
print("sum:",arr[0,0] + arr[1,-1])

2nd element of the 1st row: 1
1st element of the 2nd row: 6
sum: 7


# access the 3d array

# access the third element ofv the second array of the 3d array

In [38]:
arr = np.array([[[1,2,8,89],[4,55,65,5],[5,65,98,6]]])
print(arr[0,1,-1])



5


In [41]:
arr = np.array([[[1,2,8,89],[4,55,65,5]],[[5,65,98,6],[1,6,5,8]]])
print (arr[1,0,1])



65
